services:
  - type: web
    name: Devine_le_visage
    runtime: python
    rootDir: backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -w 2 -k gthread -b 0.0.0.0:$PORT --timeout 120"
    plan: free
